//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by diegen. DO NOT EDIT.

package v1alpha1

import (
	testing "dies.dev/testing"
	testingx "testing"
)

func TestClusterRunTemplateDie_MissingMethods(t *testingx.T) {
	die := ClusterRunTemplateBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ClusterRunTemplateDie: %s", diff.List())
	}
}
