# Copyright 2021 VMware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

project_name: cartotest

builds:
  - main: ./cmd/cartotest
    id: cartotest
    binary: cartotest
    goos:
      - darwin
      - linux
      - windows

    mod_timestamp: '{{ .CommitTimestamp }}'

    ldflags:
      - -s
      - -X github.com/vmware-tanzu/cartographer/pkg/testing.version={{.Version}}

universal_binaries:
  - replace: true

archives:
 - files:
    - src: cmd/cartotest/README.md
      strip_parent: true
    - LICENSE

release:
  github:
    owner: vmware-tanzu
    name: cartographer

  # If set to true, will not auto-publish the release.
  draft: true

  # Useful if you want to delay the creation of the tag in the remote.
  # You can create the tag locally, but not push it, and run GoReleaser.
  target_commitish: '{{ .Commit }}'

brews:
  - name: cartotest


    # NOTE: make sure the url_template, the token and given repo (github or
    # gitlab) owner and name are from the same kind.
    # We will probably unify this in the next major version like it is
    # done with scoop.

    # GitHub/GitLab repository to push the formula to
    tap:
      owner: waciumawanjohi
      name: homebrew-cartographer

      # Optionally a token can be provided, if it differs from the token
      # provided to GoReleaser
      token: "{{ .Env.GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Your app's homepage.
    homepage: "https://cartographer.sh/"

    # Template of your app's description.
    # Default is empty.
    description: "CLI to test Cartographer Templates"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache-2.0"
