builds:
  - main: ./cmd/cartotest
    id: cartotest
    binary: cartotest
    goos:
      - darwin
      - linux
      - windows

    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
 - files:
    - src: cmd/cartotest/README.md
      strip_parent: true
    - LICENSE
