//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by diegen. DO NOT EDIT.

package resources

import (
	testing "dies.dev/testing"
	testingx "testing"
)

func TestTestObjDie_MissingMethods(t *testingx.T) {
	die := TestObjBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for TestObjDie: %s", diff.List())
	}
}
