# Copyright 2021 VMware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#baseURL: "https://template.dev/"
languageCode: "en-us"
title: "Cartographer"
theme: "template"
outputs:
  home: [ "HTML", "REDIRECTS" ]
pygmentsCodefences: true
pygmentsStyle: "pygments"
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: native
    tabWidth: 4
menu:
  docs:
  - name: Overview
    url: /docs/
  #   weight: 100
  # - name: Architecture
  #   url: /docs/architecture/
  #   name: Demo
  #   url: /docs/demo/
  # - name: Scope
  #   url: /docs/scope/
  # - name: Update Images
  #   url: /docs/contributing/
params:
  twitter_url: "https://twitter.com/OssCartographer"
  github_url: "https://github.com/vmware-tanzu/cartographer"
  slack_url: "https://slack.com/"
  github_base_url: "https://github.com/vmware-tanzu/cartographer"
  use_advanced_docs: true
  docs_right_sidebar: true
  docs_search: false
  docs_search_index_name: index_name
  docs_search_api_key: api_key
  docs_versioning: true
  docs_latest: v0.0.7
  docs_versions:
    - main
    - v0.0.7
    - v0.0.6
mediaTypes:
  "text/netlify":
    delimiter: ""
outputFormats:
  REDIRECTS:
    mediaType: "text/netlify"
    baseName: "_redirects"
