# permissions for end users to edit clusterbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterbinding-editor-role
rules:
- apiGroups:
  - blueprints.carto.run
  resources:
  - clusterbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blueprints.carto.run
  resources:
  - clusterbindings/status
  verbs:
  - get
