---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - blueprints.carto.run
  resources:
  - clusterbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blueprints.carto.run
  resources:
  - clusterbindings/finalizers
  verbs:
  - update
- apiGroups:
  - blueprints.carto.run
  resources:
  - clusterbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - blueprints.carto.run
  resources:
  - clusterblueprints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blueprints.carto.run
  resources:
  - clusterblueprints/finalizers
  verbs:
  - update
- apiGroups:
  - blueprints.carto.run
  resources:
  - clusterblueprints/status
  verbs:
  - get
  - patch
  - update
