---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - blueprints.carto.run
  resources:
  - clusterblueprinttypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blueprints.carto.run
  resources:
  - clusterblueprinttypes/finalizers
  verbs:
  - update
- apiGroups:
  - blueprints.carto.run
  resources:
  - clusterblueprinttypes/status
  verbs:
  - get
  - patch
  - update
