# Copyright 2021 VMware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Source checks'
description: 'Run source code checks, linting, tests, and scans'

runs:
  using: "composite"
  steps:
    - name: check copyright header
      shell: bash
      run: |
        make copyright
        [ -z "$(git status --porcelain)" ] || git diff HEAD --exit-code

    - name: check all generables were regenerated and commited
      shell: bash
      run: |
        make gen-manifests gen-objects test-gen-manifests test-gen-objects generate
        [ -z "$(git status --porcelain)" ] || git diff HEAD --exit-code

    - name: lint
      shell: bash
      run: |
        go install github.com/get-woke/woke@latest
        make lint
        [ -z "$(git status --porcelain)" ] || git diff HEAD --exit-code

    - name: setup base dependencies
      shell: bash
      run: |
        sudo apt update && sudo apt install -y curl tar
        ./hack/ci/install-binaries.sh kubebuilder kuttl grype

    - name: run tests
      shell: bash
      env:
        KUBEBUILDER_ASSETS: /usr/local/bin
        LOG_LEVEL: "debug"
        CI: 'true'
      run: make test

    - name: scan source
      shell: bash
      run: grype .
