# Copyright 2021 VMware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-with-role-to-create-taskruns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testing-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testing-role
subjects:
  - kind: ServiceAccount
    name: service-account-with-role-to-create-taskruns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testing-role
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
      - taskruns
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carto-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carto-role
subjects:
  - kind: ServiceAccount
    name: service-account-with-role-to-create-taskruns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: carto-role
rules:
  - apiGroups:
      - carto.run
    resources:
      - runnables
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get
