// Code generated by counterfeiter. DO NOT EDIT.
package eventsfakes

import (
	"sync"

	"github.com/vmware-tanzu/cartographer/pkg/events"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

type FakeOwnerEventRecorder struct {
	AnnotatedEventfStub        func(map[string]string, string, string, string, ...interface{})
	annotatedEventfMutex       sync.RWMutex
	annotatedEventfArgsForCall []struct {
		arg1 map[string]string
		arg2 string
		arg3 string
		arg4 string
		arg5 []interface{}
	}
	EventStub        func(string, string, string)
	eventMutex       sync.RWMutex
	eventArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	EventfStub        func(string, string, string, ...interface{})
	eventfMutex       sync.RWMutex
	eventfArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 []interface{}
	}
	ResourceEventfStub        func(string, string, string, *unstructured.Unstructured, ...interface{})
	resourceEventfMutex       sync.RWMutex
	resourceEventfArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 *unstructured.Unstructured
		arg5 []interface{}
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeOwnerEventRecorder) AnnotatedEventf(arg1 map[string]string, arg2 string, arg3 string, arg4 string, arg5 ...interface{}) {
	fake.annotatedEventfMutex.Lock()
	fake.annotatedEventfArgsForCall = append(fake.annotatedEventfArgsForCall, struct {
		arg1 map[string]string
		arg2 string
		arg3 string
		arg4 string
		arg5 []interface{}
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.AnnotatedEventfStub
	fake.recordInvocation("AnnotatedEventf", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.annotatedEventfMutex.Unlock()
	if stub != nil {
		fake.AnnotatedEventfStub(arg1, arg2, arg3, arg4, arg5...)
	}
}

func (fake *FakeOwnerEventRecorder) AnnotatedEventfCallCount() int {
	fake.annotatedEventfMutex.RLock()
	defer fake.annotatedEventfMutex.RUnlock()
	return len(fake.annotatedEventfArgsForCall)
}

func (fake *FakeOwnerEventRecorder) AnnotatedEventfCalls(stub func(map[string]string, string, string, string, ...interface{})) {
	fake.annotatedEventfMutex.Lock()
	defer fake.annotatedEventfMutex.Unlock()
	fake.AnnotatedEventfStub = stub
}

func (fake *FakeOwnerEventRecorder) AnnotatedEventfArgsForCall(i int) (map[string]string, string, string, string, []interface{}) {
	fake.annotatedEventfMutex.RLock()
	defer fake.annotatedEventfMutex.RUnlock()
	argsForCall := fake.annotatedEventfArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeOwnerEventRecorder) Event(arg1 string, arg2 string, arg3 string) {
	fake.eventMutex.Lock()
	fake.eventArgsForCall = append(fake.eventArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.EventStub
	fake.recordInvocation("Event", []interface{}{arg1, arg2, arg3})
	fake.eventMutex.Unlock()
	if stub != nil {
		fake.EventStub(arg1, arg2, arg3)
	}
}

func (fake *FakeOwnerEventRecorder) EventCallCount() int {
	fake.eventMutex.RLock()
	defer fake.eventMutex.RUnlock()
	return len(fake.eventArgsForCall)
}

func (fake *FakeOwnerEventRecorder) EventCalls(stub func(string, string, string)) {
	fake.eventMutex.Lock()
	defer fake.eventMutex.Unlock()
	fake.EventStub = stub
}

func (fake *FakeOwnerEventRecorder) EventArgsForCall(i int) (string, string, string) {
	fake.eventMutex.RLock()
	defer fake.eventMutex.RUnlock()
	argsForCall := fake.eventArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeOwnerEventRecorder) Eventf(arg1 string, arg2 string, arg3 string, arg4 ...interface{}) {
	fake.eventfMutex.Lock()
	fake.eventfArgsForCall = append(fake.eventfArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 []interface{}
	}{arg1, arg2, arg3, arg4})
	stub := fake.EventfStub
	fake.recordInvocation("Eventf", []interface{}{arg1, arg2, arg3, arg4})
	fake.eventfMutex.Unlock()
	if stub != nil {
		fake.EventfStub(arg1, arg2, arg3, arg4...)
	}
}

func (fake *FakeOwnerEventRecorder) EventfCallCount() int {
	fake.eventfMutex.RLock()
	defer fake.eventfMutex.RUnlock()
	return len(fake.eventfArgsForCall)
}

func (fake *FakeOwnerEventRecorder) EventfCalls(stub func(string, string, string, ...interface{})) {
	fake.eventfMutex.Lock()
	defer fake.eventfMutex.Unlock()
	fake.EventfStub = stub
}

func (fake *FakeOwnerEventRecorder) EventfArgsForCall(i int) (string, string, string, []interface{}) {
	fake.eventfMutex.RLock()
	defer fake.eventfMutex.RUnlock()
	argsForCall := fake.eventfArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeOwnerEventRecorder) ResourceEventf(arg1 string, arg2 string, arg3 string, arg4 *unstructured.Unstructured, arg5 ...interface{}) {
	fake.resourceEventfMutex.Lock()
	fake.resourceEventfArgsForCall = append(fake.resourceEventfArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 *unstructured.Unstructured
		arg5 []interface{}
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ResourceEventfStub
	fake.recordInvocation("ResourceEventf", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.resourceEventfMutex.Unlock()
	if stub != nil {
		fake.ResourceEventfStub(arg1, arg2, arg3, arg4, arg5...)
	}
}

func (fake *FakeOwnerEventRecorder) ResourceEventfCallCount() int {
	fake.resourceEventfMutex.RLock()
	defer fake.resourceEventfMutex.RUnlock()
	return len(fake.resourceEventfArgsForCall)
}

func (fake *FakeOwnerEventRecorder) ResourceEventfCalls(stub func(string, string, string, *unstructured.Unstructured, ...interface{})) {
	fake.resourceEventfMutex.Lock()
	defer fake.resourceEventfMutex.Unlock()
	fake.ResourceEventfStub = stub
}

func (fake *FakeOwnerEventRecorder) ResourceEventfArgsForCall(i int) (string, string, string, *unstructured.Unstructured, []interface{}) {
	fake.resourceEventfMutex.RLock()
	defer fake.resourceEventfMutex.RUnlock()
	argsForCall := fake.resourceEventfArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeOwnerEventRecorder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.annotatedEventfMutex.RLock()
	defer fake.annotatedEventfMutex.RUnlock()
	fake.eventMutex.RLock()
	defer fake.eventMutex.RUnlock()
	fake.eventfMutex.RLock()
	defer fake.eventfMutex.RUnlock()
	fake.resourceEventfMutex.RLock()
	defer fake.resourceEventfMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeOwnerEventRecorder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ events.OwnerEventRecorder = new(FakeOwnerEventRecorder)
