---
apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: image-builder
spec:
  template:
    apiVersion: kpack.io/v1alpha2
    kind: Image
    metadata:
      name: $(workload.metadata.name)$
    spec:
      tag: $(params.image_prefix)$$(workload.metadata.name)$
      serviceAccountName: $(params.image-pull-sa-name)$
      builder:
        kind: ClusterBuilder
        name: my-builder
      source:
        git:
          url: $(workload.spec.source.git.url)$
          revision: $(workload.spec.source.git.ref.branch)$
  params:
    - name: image-pull-sa-name
      default: expected-service-account
    - name: image_prefix
      default: 0.0.0.0:5000/example-basic-sc- # <=== Change to proper image registry
  imagePath: .status.latestImage
