---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths": {"0.0.0.0:5000": {"username": "admin", "password": "admin"}}}' # <=== Change to proper image registry

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expected-service-account
secrets:
  - name: registry-credentials
imagePullSecrets:
  - name: registry-credentials
