// Code generated by counterfeiter. DO NOT EDIT.
package controllersfakes

import (
	"context"
	"sync"

	"github.com/vmware-tanzu/cartographer/pkg/controllers"
	"github.com/vmware-tanzu/cartographer/pkg/realizer"
	"github.com/vmware-tanzu/cartographer/pkg/realizer/statuses"
)

type FakeRealizer struct {
	RealizeStub        func(context.Context, realizer.ResourceRealizer, string, []realizer.OwnerResource, statuses.ResourceStatuses) error
	realizeMutex       sync.RWMutex
	realizeArgsForCall []struct {
		arg1 context.Context
		arg2 realizer.ResourceRealizer
		arg3 string
		arg4 []realizer.OwnerResource
		arg5 statuses.ResourceStatuses
	}
	realizeReturns struct {
		result1 error
	}
	realizeReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRealizer) Realize(arg1 context.Context, arg2 realizer.ResourceRealizer, arg3 string, arg4 []realizer.OwnerResource, arg5 statuses.ResourceStatuses) error {
	var arg4Copy []realizer.OwnerResource
	if arg4 != nil {
		arg4Copy = make([]realizer.OwnerResource, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.realizeMutex.Lock()
	ret, specificReturn := fake.realizeReturnsOnCall[len(fake.realizeArgsForCall)]
	fake.realizeArgsForCall = append(fake.realizeArgsForCall, struct {
		arg1 context.Context
		arg2 realizer.ResourceRealizer
		arg3 string
		arg4 []realizer.OwnerResource
		arg5 statuses.ResourceStatuses
	}{arg1, arg2, arg3, arg4Copy, arg5})
	stub := fake.RealizeStub
	fakeReturns := fake.realizeReturns
	fake.recordInvocation("Realize", []interface{}{arg1, arg2, arg3, arg4Copy, arg5})
	fake.realizeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRealizer) RealizeCallCount() int {
	fake.realizeMutex.RLock()
	defer fake.realizeMutex.RUnlock()
	return len(fake.realizeArgsForCall)
}

func (fake *FakeRealizer) RealizeCalls(stub func(context.Context, realizer.ResourceRealizer, string, []realizer.OwnerResource, statuses.ResourceStatuses) error) {
	fake.realizeMutex.Lock()
	defer fake.realizeMutex.Unlock()
	fake.RealizeStub = stub
}

func (fake *FakeRealizer) RealizeArgsForCall(i int) (context.Context, realizer.ResourceRealizer, string, []realizer.OwnerResource, statuses.ResourceStatuses) {
	fake.realizeMutex.RLock()
	defer fake.realizeMutex.RUnlock()
	argsForCall := fake.realizeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeRealizer) RealizeReturns(result1 error) {
	fake.realizeMutex.Lock()
	defer fake.realizeMutex.Unlock()
	fake.RealizeStub = nil
	fake.realizeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRealizer) RealizeReturnsOnCall(i int, result1 error) {
	fake.realizeMutex.Lock()
	defer fake.realizeMutex.Unlock()
	fake.RealizeStub = nil
	if fake.realizeReturnsOnCall == nil {
		fake.realizeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.realizeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRealizer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.realizeMutex.RLock()
	defer fake.realizeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRealizer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ controllers.Realizer = new(FakeRealizer)
